version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mepos_stock_db
    restart: always
    environment:
      POSTGRES_USER: mepos_user
      POSTGRES_PASSWORD: mepos_password
      POSTGRES_DB: mepos_stock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
